rem subst D: "F:\ddrive"
start "" "C:\Windows\System32\taskmgr.exe"
start "" "C:\ProgramData\chocolatey\bin\AutoHotkey.exe" "C:\Users\Timinsky\Git\rc\AutoHotKey\keyboard.ahk"
start "" "C:\ProgramData\chocolatey\bin\AutoHotkey.exe" "C:\Users\Timinsky\Git\rc\AutoHotKey\Work.ahk"
rem start "" "C:\Program Files (x86)\Dexpot\dexpot.exe"
start "" "C:\Users\TiminsKY\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Insurity\Build Status Notifier.appref-ms"
rem start "" "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE"
start "" "C:\tools\Cmder\Cmder.exe"
start "" "silentcmd.exe" "C:\Users\TiminsKY\scm-server\bin\scm-server.bat"
