choco install -y Chocolatey v0.10.15 Professional
choco install -y 7zip
choco install -y 7zip.install
choco install -y autohotkey
choco install -y autohotkey.portable
choco install -y ccleaner
choco install -y checksum
choco install -y chocolatey
choco install -y chocolatey-core.extension
choco install -y chocolatey-dotnetfx.extension
choco install -y chocolatey-visualstudio.extension
choco install -y chocolatey-vscode.extension
choco install -y chocolatey-windowsupdate.extension
choco install -y chocolatey.extension
choco install -y chocolatey.server
choco install -y chocolateygui
choco install -y cloc
choco install -y dexpot
choco install -y dotnetcore-runtime.install
choco install -y dotnetcore-sdk
choco install -y dotnetfx
choco install -y dotPeek
choco install -y filezilla
choco install -y microsoft-teams
choco install -y mRemoteNG
choco install -y nodejs
choco install -y nodejs.install
choco install -y nuget.commandline
choco install -y NugetPackageExplorer
choco install -y Opera
choco install -y Pester
choco install -y python2
choco install -y python3
choco install -y pip
choco install -y poshgit
choco install -y postman
choco install -y rainmeter
choco install -y silentcmd
choco install -y sysinternals
choco install -y tortoisegit
choco install -y 39 packages installed.
