choco upgrade -y autohotkey
choco upgrade -y autohotkey.portable
choco upgrade -y ccleaner
choco install -y checksum
choco upgrade -y chocolatey
choco upgrade -y chocolatey-core.extension
choco upgrade -y chocolatey-dotnetfx.extension
choco upgrade -y chocolatey-visualstudio.extension
choco upgrade -y chocolatey-vscode.extension
choco upgrade -y chocolatey-windowsupdate.extension
choco upgrade -y chocolatey.extension
choco upgrade -y chocolatey.server
choco upgrade -y chocolateygui
choco install -y cloc
choco install -y dexpot
choco install -y dotnetcore-runtime.install
choco install -y dotnetcore-sdk
choco install -y dotnetfx
choco install -y dotPeek
choco install -y filezilla
choco upgrade -y microsoft-teams
choco install -y mRemoteNG
choco install -y nodejs
choco install -y nodejs.install
choco install -y nuget.commandline
choco install -y NugetPackageExplorer
choco install -y Opera
choco install -y Pester
choco install -y python2
choco install -y python3
choco install -y pip
choco install -y poshgit
choco install -y postman
choco install -y rainmeter
choco install -y silentcmd
choco install -y sysinternals
choco install -y tortoisegit
choco install -y 37 packages installed.
